package org.dao;

import org.apache.ibatis.annotations.Param;
import org.entity.dto.AdminLookAgencyExample;
import org.entity.dto.AdminLookAgencyKey;

import java.util.List;

public interface AdminLookAgencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_look_agency
     *
     * @mbggenerated
     */
    int countByExample(AdminLookAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_look_agency
     *
     * @mbggenerated
     */
    int deleteByExample(AdminLookAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_look_agency
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AdminLookAgencyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_look_agency
     *
     * @mbggenerated
     */
    int insert(AdminLookAgencyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_look_agency
     *
     * @mbggenerated
     */
    int insertSelective(AdminLookAgencyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_look_agency
     *
     * @mbggenerated
     */
    List<AdminLookAgencyKey> selectByExample(AdminLookAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_look_agency
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdminLookAgencyKey record, @Param("example") AdminLookAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_look_agency
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdminLookAgencyKey record, @Param("example") AdminLookAgencyExample example);
}