package org.dao;

import org.apache.ibatis.annotations.Param;
import org.entity.dto.CouponUse;
import org.entity.dto.CouponUseExample;
import org.entity.dto.CouponUse;
import org.entity.dto.CouponUseExample;

import java.util.List;

public interface CouponUseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    int countByExample(CouponUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    int deleteByExample(CouponUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long couponUseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    int insert(CouponUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    int insertSelective(CouponUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    List<CouponUse> selectByExample(CouponUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    CouponUse selectByPrimaryKey(Long couponUseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CouponUse record, @Param("example") CouponUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CouponUse record, @Param("example") CouponUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CouponUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CouponUse record);

    //连表
    List<CouponUse> selectUnionByExample(CouponUseExample example);
    int countUnionByExample(CouponUseExample example);
}