package org.dao;

import org.apache.ibatis.annotations.Param;
import org.entity.dto.CouponScheme;
import org.entity.dto.CouponSchemeExample;

import java.util.List;

public interface CouponSchemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    int countByExample(CouponSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    int deleteByExample(CouponSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    int insert(CouponScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    int insertSelective(CouponScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    List<CouponScheme> selectByExample(CouponSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    CouponScheme selectByPrimaryKey(Long planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CouponScheme record, @Param("example") CouponSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CouponScheme record, @Param("example") CouponSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CouponScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CouponScheme record);

    /**
     * 联合查找
     * @param example
     * @return
     */
    List<CouponScheme> selectUnionByExample(CouponSchemeExample example);

    int countUnionByExample(CouponSchemeExample example);

    CouponScheme selectUnionByPrimaryKey(Long planId);
}