package org.dao;

import org.apache.ibatis.annotations.Param;
import org.entity.dto.Coupon;
import org.entity.dto.CouponExample;

import java.util.List;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    int countByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    int deleteByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    List<Coupon> selectByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    Coupon selectByPrimaryKey(Long couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Coupon record, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Coupon record, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Coupon record);
}