package org.dao;

import org.apache.ibatis.annotations.Param;
import org.entity.dto.GuideAgencyInfos;
import org.entity.dto.GuideAgencyInfosExample;

import java.util.List;

public interface GuideAgencyInfosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    int countByExample(GuideAgencyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    int deleteByExample(GuideAgencyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long guideAgencyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    int insert(GuideAgencyInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    int insertSelective(GuideAgencyInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    List<GuideAgencyInfos> selectByExample(GuideAgencyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    GuideAgencyInfos selectByPrimaryKey(Long guideAgencyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GuideAgencyInfos record, @Param("example") GuideAgencyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GuideAgencyInfos record, @Param("example") GuideAgencyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GuideAgencyInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GuideAgencyInfos record);

    /**
     * 联合查询
     * @param example
     * @return
     */
    List<GuideAgencyInfos> selectUnionByExample(GuideAgencyInfosExample example);
}