package org.dao;

import org.apache.ibatis.annotations.Param;
import org.entity.dto.GuideGroupUser;
import org.entity.dto.GuideGroupUserExample;

import java.util.List;

public interface GuideGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    int countByExample(GuideGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    int deleteByExample(GuideGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    int insert(GuideGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    int insertSelective(GuideGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    List<GuideGroupUser> selectByExample(GuideGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    GuideGroupUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GuideGroupUser record, @Param("example") GuideGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GuideGroupUser record, @Param("example") GuideGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GuideGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GuideGroupUser record);
}