package org.dao;

import org.apache.ibatis.annotations.Param;
import org.entity.dto.GuideGroupInfos;
import org.entity.dto.GuideGroupInfosExample;

import java.util.List;

public interface GuideGroupInfosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    int countByExample(GuideGroupInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    int deleteByExample(GuideGroupInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long guideGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    int insert(GuideGroupInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    int insertSelective(GuideGroupInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    List<GuideGroupInfos> selectByExample(GuideGroupInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    GuideGroupInfos selectByPrimaryKey(Long guideGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GuideGroupInfos record, @Param("example") GuideGroupInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GuideGroupInfos record, @Param("example") GuideGroupInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GuideGroupInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GuideGroupInfos record);
    /**
     * 联表查询
     * 1. 加入admin表信息
     * 2. 加入旅行社表信息
     * @param example
     * @return
     */
    int countUnionByExample(GuideGroupInfosExample example);
    List<GuideGroupInfos> selectUnionByExample(GuideGroupInfosExample example);

    /**
     * 根据导游id查询
     */
    List<GuideGroupInfos> selectByGuideId(Long guideId);

    /**
     * 根据groupid查询
     */
    GuideGroupInfos selectByGroupId(Long groupId);

    /**
     * 根据groupid查询
     */
    List<GuideGroupInfos> selectByGroupIds(@Param("groupIds") List<Long> groupIds);


}