package org.entity.dto;

import java.io.Serializable;

public class AdminLookAgencyKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_look_agency.admin_id
     *
     * @mbggenerated
     */
    private Long adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_look_agency.agency_id
     *
     * @mbggenerated
     */
    private Long agencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_look_agency
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_look_agency.admin_id
     *
     * @return the value of admin_look_agency.admin_id
     *
     * @mbggenerated
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_look_agency.admin_id
     *
     * @param adminId the value for admin_look_agency.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_look_agency.agency_id
     *
     * @return the value of admin_look_agency.agency_id
     *
     * @mbggenerated
     */
    public Long getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_look_agency.agency_id
     *
     * @param agencyId the value for admin_look_agency.agency_id
     *
     * @mbggenerated
     */
    public void setAgencyId(Long agencyId) {
        this.agencyId = agencyId;
    }
}