package org.entity.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Coupon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_id
     *
     * @mbggenerated
     */
    private Long couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_name
     *
     * @mbggenerated
     */
    private String couponName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_time
     *
     * @mbggenerated
     */
    private Integer couponTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_money
     *
     * @mbggenerated
     */
    private BigDecimal couponMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_start_time
     *
     * @mbggenerated
     */
    private Date couponStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_create_time
     *
     * @mbggenerated
     */
    private Date couponCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_is_validity
     *
     * @mbggenerated
     */
    private Integer couponIsValidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_validity_time
     *
     * @mbggenerated
     */
    private Integer couponValidityTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_state
     *
     * @mbggenerated
     */
    private Integer couponState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_end_time
     *
     * @mbggenerated
     */
    private Date couponEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_is_condition
     *
     * @mbggenerated
     */
    private Integer couponIsCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_start_money
     *
     * @mbggenerated
     */
    private BigDecimal couponStartMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_type
     *
     * @mbggenerated
     */
    private Integer couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_list.coupon_need_deposit
     *
     * @mbggenerated
     */
    private Integer couponNeedDeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_list
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_id
     *
     * @return the value of coupon_list.coupon_id
     *
     * @mbggenerated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_id
     *
     * @param couponId the value for coupon_list.coupon_id
     *
     * @mbggenerated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_name
     *
     * @return the value of coupon_list.coupon_name
     *
     * @mbggenerated
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_name
     *
     * @param couponName the value for coupon_list.coupon_name
     *
     * @mbggenerated
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_time
     *
     * @return the value of coupon_list.coupon_time
     *
     * @mbggenerated
     */
    public Integer getCouponTime() {
        return couponTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_time
     *
     * @param couponTime the value for coupon_list.coupon_time
     *
     * @mbggenerated
     */
    public void setCouponTime(Integer couponTime) {
        this.couponTime = couponTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_money
     *
     * @return the value of coupon_list.coupon_money
     *
     * @mbggenerated
     */
    public BigDecimal getCouponMoney() {
        return couponMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_money
     *
     * @param couponMoney the value for coupon_list.coupon_money
     *
     * @mbggenerated
     */
    public void setCouponMoney(BigDecimal couponMoney) {
        this.couponMoney = couponMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_start_time
     *
     * @return the value of coupon_list.coupon_start_time
     *
     * @mbggenerated
     */
    public Date getCouponStartTime() {
        return couponStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_start_time
     *
     * @param couponStartTime the value for coupon_list.coupon_start_time
     *
     * @mbggenerated
     */
    public void setCouponStartTime(Date couponStartTime) {
        this.couponStartTime = couponStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_create_time
     *
     * @return the value of coupon_list.coupon_create_time
     *
     * @mbggenerated
     */
    public Date getCouponCreateTime() {
        return couponCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_create_time
     *
     * @param couponCreateTime the value for coupon_list.coupon_create_time
     *
     * @mbggenerated
     */
    public void setCouponCreateTime(Date couponCreateTime) {
        this.couponCreateTime = couponCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_is_validity
     *
     * @return the value of coupon_list.coupon_is_validity
     *
     * @mbggenerated
     */
    public Integer getCouponIsValidity() {
        return couponIsValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_is_validity
     *
     * @param couponIsValidity the value for coupon_list.coupon_is_validity
     *
     * @mbggenerated
     */
    public void setCouponIsValidity(Integer couponIsValidity) {
        this.couponIsValidity = couponIsValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_validity_time
     *
     * @return the value of coupon_list.coupon_validity_time
     *
     * @mbggenerated
     */
    public Integer getCouponValidityTime() {
        return couponValidityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_validity_time
     *
     * @param couponValidityTime the value for coupon_list.coupon_validity_time
     *
     * @mbggenerated
     */
    public void setCouponValidityTime(Integer couponValidityTime) {
        this.couponValidityTime = couponValidityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_state
     *
     * @return the value of coupon_list.coupon_state
     *
     * @mbggenerated
     */
    public Integer getCouponState() {
        return couponState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_state
     *
     * @param couponState the value for coupon_list.coupon_state
     *
     * @mbggenerated
     */
    public void setCouponState(Integer couponState) {
        this.couponState = couponState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_end_time
     *
     * @return the value of coupon_list.coupon_end_time
     *
     * @mbggenerated
     */
    public Date getCouponEndTime() {
        return couponEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_end_time
     *
     * @param couponEndTime the value for coupon_list.coupon_end_time
     *
     * @mbggenerated
     */
    public void setCouponEndTime(Date couponEndTime) {
        this.couponEndTime = couponEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_is_condition
     *
     * @return the value of coupon_list.coupon_is_condition
     *
     * @mbggenerated
     */
    public Integer getCouponIsCondition() {
        return couponIsCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_is_condition
     *
     * @param couponIsCondition the value for coupon_list.coupon_is_condition
     *
     * @mbggenerated
     */
    public void setCouponIsCondition(Integer couponIsCondition) {
        this.couponIsCondition = couponIsCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_start_money
     *
     * @return the value of coupon_list.coupon_start_money
     *
     * @mbggenerated
     */
    public BigDecimal getCouponStartMoney() {
        return couponStartMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_start_money
     *
     * @param couponStartMoney the value for coupon_list.coupon_start_money
     *
     * @mbggenerated
     */
    public void setCouponStartMoney(BigDecimal couponStartMoney) {
        this.couponStartMoney = couponStartMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_type
     *
     * @return the value of coupon_list.coupon_type
     *
     * @mbggenerated
     */
    public Integer getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_type
     *
     * @param couponType the value for coupon_list.coupon_type
     *
     * @mbggenerated
     */
    public void setCouponType(Integer couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_list.coupon_need_deposit
     *
     * @return the value of coupon_list.coupon_need_deposit
     *
     * @mbggenerated
     */
    public Integer getCouponNeedDeposit() {
        return couponNeedDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_list.coupon_need_deposit
     *
     * @param couponNeedDeposit the value for coupon_list.coupon_need_deposit
     *
     * @mbggenerated
     */
    public void setCouponNeedDeposit(Integer couponNeedDeposit) {
        this.couponNeedDeposit = couponNeedDeposit;
    }
}