package org.entity.dto;

import java.io.Serializable;
import java.util.Date;

public class CouponScheme implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_id
     *
     * @mbggenerated
     */
    private Long planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_name
     *
     * @mbggenerated
     */
    private String planName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_create_time
     *
     * @mbggenerated
     */
    private Date planCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_redeem_code
     *
     * @mbggenerated
     */
    private String planRedeemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_redeem_nums
     *
     * @mbggenerated
     */
    private Integer planRedeemNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_coupon_id
     *
     * @mbggenerated
     */
    private Long planCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_online_time
     *
     * @mbggenerated
     */
    private Date planOnlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_offline_time
     *
     * @mbggenerated
     */
    private Date planOfflineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_state
     *
     * @mbggenerated
     */
    private Integer planState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_surplus_nums
     *
     * @mbggenerated
     */
    private Integer planSurplusNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_used_nums
     *
     * @mbggenerated
     */
    private Integer planUsedNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_reserve_online_time
     *
     * @mbggenerated
     */
    private Date planReserveOnlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_reserve_offline_time
     *
     * @mbggenerated
     */
    private Date planReserveOfflineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_scheme.plan_type
     *
     * @mbggenerated
     */
    private Integer planType;


    /**
     * 方案关联的骑行券
     */
    private Coupon coupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_scheme
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_id
     *
     * @return the value of coupon_scheme.plan_id
     *
     * @mbggenerated
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_id
     *
     * @param planId the value for coupon_scheme.plan_id
     *
     * @mbggenerated
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_name
     *
     * @return the value of coupon_scheme.plan_name
     *
     * @mbggenerated
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_name
     *
     * @param planName the value for coupon_scheme.plan_name
     *
     * @mbggenerated
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_create_time
     *
     * @return the value of coupon_scheme.plan_create_time
     *
     * @mbggenerated
     */
    public Date getPlanCreateTime() {
        return planCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_create_time
     *
     * @param planCreateTime the value for coupon_scheme.plan_create_time
     *
     * @mbggenerated
     */
    public void setPlanCreateTime(Date planCreateTime) {
        this.planCreateTime = planCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_redeem_code
     *
     * @return the value of coupon_scheme.plan_redeem_code
     *
     * @mbggenerated
     */
    public String getPlanRedeemCode() {
        return planRedeemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_redeem_code
     *
     * @param planRedeemCode the value for coupon_scheme.plan_redeem_code
     *
     * @mbggenerated
     */
    public void setPlanRedeemCode(String planRedeemCode) {
        this.planRedeemCode = planRedeemCode == null ? null : planRedeemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_redeem_nums
     *
     * @return the value of coupon_scheme.plan_redeem_nums
     *
     * @mbggenerated
     */
    public Integer getPlanRedeemNums() {
        return planRedeemNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_redeem_nums
     *
     * @param planRedeemNums the value for coupon_scheme.plan_redeem_nums
     *
     * @mbggenerated
     */
    public void setPlanRedeemNums(Integer planRedeemNums) {
        this.planRedeemNums = planRedeemNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_coupon_id
     *
     * @return the value of coupon_scheme.plan_coupon_id
     *
     * @mbggenerated
     */
    public Long getPlanCouponId() {
        return planCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_coupon_id
     *
     * @param planCouponId the value for coupon_scheme.plan_coupon_id
     *
     * @mbggenerated
     */
    public void setPlanCouponId(Long planCouponId) {
        this.planCouponId = planCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_online_time
     *
     * @return the value of coupon_scheme.plan_online_time
     *
     * @mbggenerated
     */
    public Date getPlanOnlineTime() {
        return planOnlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_online_time
     *
     * @param planOnlineTime the value for coupon_scheme.plan_online_time
     *
     * @mbggenerated
     */
    public void setPlanOnlineTime(Date planOnlineTime) {
        this.planOnlineTime = planOnlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_offline_time
     *
     * @return the value of coupon_scheme.plan_offline_time
     *
     * @mbggenerated
     */
    public Date getPlanOfflineTime() {
        return planOfflineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_offline_time
     *
     * @param planOfflineTime the value for coupon_scheme.plan_offline_time
     *
     * @mbggenerated
     */
    public void setPlanOfflineTime(Date planOfflineTime) {
        this.planOfflineTime = planOfflineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_state
     *
     * @return the value of coupon_scheme.plan_state
     *
     * @mbggenerated
     */
    public Integer getPlanState() {
        return planState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_state
     *
     * @param planState the value for coupon_scheme.plan_state
     *
     * @mbggenerated
     */
    public void setPlanState(Integer planState) {
        this.planState = planState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_surplus_nums
     *
     * @return the value of coupon_scheme.plan_surplus_nums
     *
     * @mbggenerated
     */
    public Integer getPlanSurplusNums() {
        return planSurplusNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_surplus_nums
     *
     * @param planSurplusNums the value for coupon_scheme.plan_surplus_nums
     *
     * @mbggenerated
     */
    public void setPlanSurplusNums(Integer planSurplusNums) {
        this.planSurplusNums = planSurplusNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_used_nums
     *
     * @return the value of coupon_scheme.plan_used_nums
     *
     * @mbggenerated
     */
    public Integer getPlanUsedNums() {
        return planUsedNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_used_nums
     *
     * @param planUsedNums the value for coupon_scheme.plan_used_nums
     *
     * @mbggenerated
     */
    public void setPlanUsedNums(Integer planUsedNums) {
        this.planUsedNums = planUsedNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_reserve_online_time
     *
     * @return the value of coupon_scheme.plan_reserve_online_time
     *
     * @mbggenerated
     */
    public Date getPlanReserveOnlineTime() {
        return planReserveOnlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_reserve_online_time
     *
     * @param planReserveOnlineTime the value for coupon_scheme.plan_reserve_online_time
     *
     * @mbggenerated
     */
    public void setPlanReserveOnlineTime(Date planReserveOnlineTime) {
        this.planReserveOnlineTime = planReserveOnlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_reserve_offline_time
     *
     * @return the value of coupon_scheme.plan_reserve_offline_time
     *
     * @mbggenerated
     */
    public Date getPlanReserveOfflineTime() {
        return planReserveOfflineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_reserve_offline_time
     *
     * @param planReserveOfflineTime the value for coupon_scheme.plan_reserve_offline_time
     *
     * @mbggenerated
     */
    public void setPlanReserveOfflineTime(Date planReserveOfflineTime) {
        this.planReserveOfflineTime = planReserveOfflineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_scheme.plan_type
     *
     * @return the value of coupon_scheme.plan_type
     *
     * @mbggenerated
     */
    public Integer getPlanType() {
        return planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_scheme.plan_type
     *
     * @param planType the value for coupon_scheme.plan_type
     *
     * @mbggenerated
     */
    public void setPlanType(Integer planType) {
        this.planType = planType;
    }

    public Coupon getCoupon() {
        return coupon;
    }

    public void setCoupon(Coupon coupon) {
        this.coupon = coupon;
    }
}