package org.entity.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CouponUseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */

    protected Integer limitStart;
    protected Integer limitEnd;

    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    public Integer getLimitStart() {
        return limitStart;
    }

    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    public Integer getLimitEnd() {
        return limitEnd;
    }

    public CouponUseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCouponUseIdIsNull() {
            addCriterion("coupon_use_id is null");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdIsNotNull() {
            addCriterion("coupon_use_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdEqualTo(Long value) {
            addCriterion("coupon_use_id =", value, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdNotEqualTo(Long value) {
            addCriterion("coupon_use_id <>", value, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdGreaterThan(Long value) {
            addCriterion("coupon_use_id >", value, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_use_id >=", value, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdLessThan(Long value) {
            addCriterion("coupon_use_id <", value, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdLessThanOrEqualTo(Long value) {
            addCriterion("coupon_use_id <=", value, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdIn(List<Long> values) {
            addCriterion("coupon_use_id in", values, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdNotIn(List<Long> values) {
            addCriterion("coupon_use_id not in", values, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdBetween(Long value1, Long value2) {
            addCriterion("coupon_use_id between", value1, value2, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponUseIdNotBetween(Long value1, Long value2) {
            addCriterion("coupon_use_id not between", value1, value2, "couponUseId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdIsNull() {
            addCriterion("coupon_scheme_id is null");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdIsNotNull() {
            addCriterion("coupon_scheme_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdEqualTo(Long value) {
            addCriterion("coupon_scheme_id =", value, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdNotEqualTo(Long value) {
            addCriterion("coupon_scheme_id <>", value, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdGreaterThan(Long value) {
            addCriterion("coupon_scheme_id >", value, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_scheme_id >=", value, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdLessThan(Long value) {
            addCriterion("coupon_scheme_id <", value, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdLessThanOrEqualTo(Long value) {
            addCriterion("coupon_scheme_id <=", value, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdIn(List<Long> values) {
            addCriterion("coupon_scheme_id in", values, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdNotIn(List<Long> values) {
            addCriterion("coupon_scheme_id not in", values, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdBetween(Long value1, Long value2) {
            addCriterion("coupon_scheme_id between", value1, value2, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCouponSchemeIdNotBetween(Long value1, Long value2) {
            addCriterion("coupon_scheme_id not between", value1, value2, "couponSchemeId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon_use
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon_use
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}