package org.entity.dto;

import java.io.Serializable;
import java.util.Date;

public class CouponToUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_to_user.coupon_user_id
     *
     * @mbggenerated
     */
    private Long couponUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_to_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_to_user.plan_id
     *
     * @mbggenerated
     */
    private Long planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_to_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_to_user.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_to_user.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_to_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_to_user.coupon_user_id
     *
     * @return the value of coupon_to_user.coupon_user_id
     *
     * @mbggenerated
     */
    public Long getCouponUserId() {
        return couponUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_to_user.coupon_user_id
     *
     * @param couponUserId the value for coupon_to_user.coupon_user_id
     *
     * @mbggenerated
     */
    public void setCouponUserId(Long couponUserId) {
        this.couponUserId = couponUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_to_user.user_id
     *
     * @return the value of coupon_to_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_to_user.user_id
     *
     * @param userId the value for coupon_to_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_to_user.plan_id
     *
     * @return the value of coupon_to_user.plan_id
     *
     * @mbggenerated
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_to_user.plan_id
     *
     * @param planId the value for coupon_to_user.plan_id
     *
     * @mbggenerated
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_to_user.create_time
     *
     * @return the value of coupon_to_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_to_user.create_time
     *
     * @param createTime the value for coupon_to_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_to_user.state
     *
     * @return the value of coupon_to_user.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_to_user.state
     *
     * @param state the value for coupon_to_user.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_to_user.end_time
     *
     * @return the value of coupon_to_user.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_to_user.end_time
     *
     * @param endTime the value for coupon_to_user.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}