package org.entity.dto;

import java.io.Serializable;

public class GuideAgencyInfos implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_id
     *
     * @mbggenerated
     */
    private Long guideAgencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_name
     *
     * @mbggenerated
     */
    private String guideAgencyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_principal_id
     *
     * @mbggenerated
     */
    private Long guideAgencyPrincipalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_riding_count
     *
     * @mbggenerated
     */
    private Long guideAgencyRidingCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_remark
     *
     * @mbggenerated
     */
    private String guideAgencyRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_creator_id
     *
     * @mbggenerated
     */
    private Long guideAgencyCreatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_scenic
     *
     * @mbggenerated
     */
    private String guideAgencyScenic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_addr
     *
     * @mbggenerated
     */
    private String guideAgencyAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_city_id
     *
     * @mbggenerated
     */
    private Long guideAgencyCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_province_id
     *
     * @mbggenerated
     */
    private Long guideAgencyProvinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_agency_infos.guide_agency_manager_id
     *
     * @mbggenerated
     */
    private Long guideAgencyManagerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    private Admin creatorAdmin;

    private Admin principalAdmin;

    private Admin managerAdmin;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_id
     *
     * @return the value of guide_agency_infos.guide_agency_id
     *
     * @mbggenerated
     */
    public Long getGuideAgencyId() {
        return guideAgencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_id
     *
     * @param guideAgencyId the value for guide_agency_infos.guide_agency_id
     *
     * @mbggenerated
     */
    public void setGuideAgencyId(Long guideAgencyId) {
        this.guideAgencyId = guideAgencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_name
     *
     * @return the value of guide_agency_infos.guide_agency_name
     *
     * @mbggenerated
     */
    public String getGuideAgencyName() {
        return guideAgencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_name
     *
     * @param guideAgencyName the value for guide_agency_infos.guide_agency_name
     *
     * @mbggenerated
     */
    public void setGuideAgencyName(String guideAgencyName) {
        this.guideAgencyName = guideAgencyName == null ? null : guideAgencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_principal_id
     *
     * @return the value of guide_agency_infos.guide_agency_principal_id
     *
     * @mbggenerated
     */
    public Long getGuideAgencyPrincipalId() {
        return guideAgencyPrincipalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_principal_id
     *
     * @param guideAgencyPrincipalId the value for guide_agency_infos.guide_agency_principal_id
     *
     * @mbggenerated
     */
    public void setGuideAgencyPrincipalId(Long guideAgencyPrincipalId) {
        this.guideAgencyPrincipalId = guideAgencyPrincipalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_riding_count
     *
     * @return the value of guide_agency_infos.guide_agency_riding_count
     *
     * @mbggenerated
     */
    public Long getGuideAgencyRidingCount() {
        return guideAgencyRidingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_riding_count
     *
     * @param guideAgencyRidingCount the value for guide_agency_infos.guide_agency_riding_count
     *
     * @mbggenerated
     */
    public void setGuideAgencyRidingCount(Long guideAgencyRidingCount) {
        this.guideAgencyRidingCount = guideAgencyRidingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_remark
     *
     * @return the value of guide_agency_infos.guide_agency_remark
     *
     * @mbggenerated
     */
    public String getGuideAgencyRemark() {
        return guideAgencyRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_remark
     *
     * @param guideAgencyRemark the value for guide_agency_infos.guide_agency_remark
     *
     * @mbggenerated
     */
    public void setGuideAgencyRemark(String guideAgencyRemark) {
        this.guideAgencyRemark = guideAgencyRemark == null ? null : guideAgencyRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_creator_id
     *
     * @return the value of guide_agency_infos.guide_agency_creator_id
     *
     * @mbggenerated
     */
    public Long getGuideAgencyCreatorId() {
        return guideAgencyCreatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_creator_id
     *
     * @param guideAgencyCreatorId the value for guide_agency_infos.guide_agency_creator_id
     *
     * @mbggenerated
     */
    public void setGuideAgencyCreatorId(Long guideAgencyCreatorId) {
        this.guideAgencyCreatorId = guideAgencyCreatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_scenic
     *
     * @return the value of guide_agency_infos.guide_agency_scenic
     *
     * @mbggenerated
     */
    public String getGuideAgencyScenic() {
        return guideAgencyScenic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_scenic
     *
     * @param guideAgencyScenic the value for guide_agency_infos.guide_agency_scenic
     *
     * @mbggenerated
     */
    public void setGuideAgencyScenic(String guideAgencyScenic) {
        this.guideAgencyScenic = guideAgencyScenic == null ? null : guideAgencyScenic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_addr
     *
     * @return the value of guide_agency_infos.guide_agency_addr
     *
     * @mbggenerated
     */
    public String getGuideAgencyAddr() {
        return guideAgencyAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_addr
     *
     * @param guideAgencyAddr the value for guide_agency_infos.guide_agency_addr
     *
     * @mbggenerated
     */
    public void setGuideAgencyAddr(String guideAgencyAddr) {
        this.guideAgencyAddr = guideAgencyAddr == null ? null : guideAgencyAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_city_id
     *
     * @return the value of guide_agency_infos.guide_agency_city_id
     *
     * @mbggenerated
     */
    public Long getGuideAgencyCityId() {
        return guideAgencyCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_city_id
     *
     * @param guideAgencyCityId the value for guide_agency_infos.guide_agency_city_id
     *
     * @mbggenerated
     */
    public void setGuideAgencyCityId(Long guideAgencyCityId) {
        this.guideAgencyCityId = guideAgencyCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_province_id
     *
     * @return the value of guide_agency_infos.guide_agency_province_id
     *
     * @mbggenerated
     */
    public Long getGuideAgencyProvinceId() {
        return guideAgencyProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_province_id
     *
     * @param guideAgencyProvinceId the value for guide_agency_infos.guide_agency_province_id
     *
     * @mbggenerated
     */
    public void setGuideAgencyProvinceId(Long guideAgencyProvinceId) {
        this.guideAgencyProvinceId = guideAgencyProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_agency_infos.guide_agency_manager_id
     *
     * @return the value of guide_agency_infos.guide_agency_manager_id
     *
     * @mbggenerated
     */
    public Long getGuideAgencyManagerId() {
        return guideAgencyManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_agency_infos.guide_agency_manager_id
     *
     * @param guideAgencyManagerId the value for guide_agency_infos.guide_agency_manager_id
     *
     * @mbggenerated
     */
    public void setGuideAgencyManagerId(Long guideAgencyManagerId) {
        this.guideAgencyManagerId = guideAgencyManagerId;
    }

    public Admin getCreatorAdmin() {
        return creatorAdmin;
    }

    public void setCreatorAdmin(Admin creatorAdmin) {
        this.creatorAdmin = creatorAdmin;
    }

    public Admin getPrincipalAdmin() {
        return principalAdmin;
    }

    public void setPrincipalAdmin(Admin principalAdmin) {
        this.principalAdmin = principalAdmin;
    }

    public Admin getManagerAdmin() {
        return managerAdmin;
    }

    public void setManagerAdmin(Admin managerAdmin) {
        this.managerAdmin = managerAdmin;
    }
}