package org.entity.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class GuideGroupInfos implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_id
     *
     * @mbggenerated
     */
    private Long guideGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_id
     *
     * @mbggenerated
     */
    private Long guideId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_start_time
     *
     * @mbggenerated
     */
    private Date guideGroupStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_scenic
     *
     * @mbggenerated
     */
    private String guideGroupScenic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_headcount
     *
     * @mbggenerated
     */
    private Integer guideGroupHeadcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_ridingcount
     *
     * @mbggenerated
     */
    private Integer guideGroupRidingcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_state
     *
     * @mbggenerated
     */
    private Integer guideGroupState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_remark
     *
     * @mbggenerated
     */
    private String guideGroupRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_creator_id
     *
     * @mbggenerated
     */
    private Long guideGroupCreatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_coupon_count
     *
     * @mbggenerated
     */
    private Integer guideGroupCouponCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_coupon_state
     *
     * @mbggenerated
     */
    private Integer guideGroupCouponState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_coupon_publishtime
     *
     * @mbggenerated
     */
    private Date guideGroupCouponPublishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_coupon_id
     *
     * @mbggenerated
     */
    private Long guideGroupCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_agency_id
     *
     * @mbggenerated
     */
    private Long guideGroupAgencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_infos.guide_group_end_time
     *
     * @mbggenerated
     */
    private Date guideGroupEndTime;

    private String guideGroupCouponInfo;

    /**
     * 需要联表查询旅行社的信息
     */
    private GuideAgencyInfos guideAgencyInfos;

    /**
     * 需要联表查询管理员(导游)信息
     */
    private Admin admin;

    /**
     * 需要联表查询团下游客列表
     */
    private List<User> users;

    /**
     * 需要联表查询骑行券方案
     */
    private CouponScheme couponScheme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_id
     *
     * @return the value of guide_group_infos.guide_group_id
     *
     * @mbggenerated
     */
    public Long getGuideGroupId() {
        return guideGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_id
     *
     * @param guideGroupId the value for guide_group_infos.guide_group_id
     *
     * @mbggenerated
     */
    public void setGuideGroupId(Long guideGroupId) {
        this.guideGroupId = guideGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_id
     *
     * @return the value of guide_group_infos.guide_id
     *
     * @mbggenerated
     */
    public Long getGuideId() {
        return guideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_id
     *
     * @param guideId the value for guide_group_infos.guide_id
     *
     * @mbggenerated
     */
    public void setGuideId(Long guideId) {
        this.guideId = guideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_start_time
     *
     * @return the value of guide_group_infos.guide_group_start_time
     *
     * @mbggenerated
     */
    public Date getGuideGroupStartTime() {
        return guideGroupStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_start_time
     *
     * @param guideGroupStartTime the value for guide_group_infos.guide_group_start_time
     *
     * @mbggenerated
     */
    public void setGuideGroupStartTime(Date guideGroupStartTime) {
        this.guideGroupStartTime = guideGroupStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_scenic
     *
     * @return the value of guide_group_infos.guide_group_scenic
     *
     * @mbggenerated
     */
    public String getGuideGroupScenic() {
        return guideGroupScenic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_scenic
     *
     * @param guideGroupScenic the value for guide_group_infos.guide_group_scenic
     *
     * @mbggenerated
     */
    public void setGuideGroupScenic(String guideGroupScenic) {
        this.guideGroupScenic = guideGroupScenic == null ? null : guideGroupScenic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_headcount
     *
     * @return the value of guide_group_infos.guide_group_headcount
     *
     * @mbggenerated
     */
    public Integer getGuideGroupHeadcount() {
        return guideGroupHeadcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_headcount
     *
     * @param guideGroupHeadcount the value for guide_group_infos.guide_group_headcount
     *
     * @mbggenerated
     */
    public void setGuideGroupHeadcount(Integer guideGroupHeadcount) {
        this.guideGroupHeadcount = guideGroupHeadcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_ridingcount
     *
     * @return the value of guide_group_infos.guide_group_ridingcount
     *
     * @mbggenerated
     */
    public Integer getGuideGroupRidingcount() {
        return guideGroupRidingcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_ridingcount
     *
     * @param guideGroupRidingcount the value for guide_group_infos.guide_group_ridingcount
     *
     * @mbggenerated
     */
    public void setGuideGroupRidingcount(Integer guideGroupRidingcount) {
        this.guideGroupRidingcount = guideGroupRidingcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_state
     *
     * @return the value of guide_group_infos.guide_group_state
     *
     * @mbggenerated
     */
    public Integer getGuideGroupState() {
        return guideGroupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_state
     *
     * @param guideGroupState the value for guide_group_infos.guide_group_state
     *
     * @mbggenerated
     */
    public void setGuideGroupState(Integer guideGroupState) {
        this.guideGroupState = guideGroupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_remark
     *
     * @return the value of guide_group_infos.guide_group_remark
     *
     * @mbggenerated
     */
    public String getGuideGroupRemark() {
        return guideGroupRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_remark
     *
     * @param guideGroupRemark the value for guide_group_infos.guide_group_remark
     *
     * @mbggenerated
     */
    public void setGuideGroupRemark(String guideGroupRemark) {
        this.guideGroupRemark = guideGroupRemark == null ? null : guideGroupRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_creator_id
     *
     * @return the value of guide_group_infos.guide_group_creator_id
     *
     * @mbggenerated
     */
    public Long getGuideGroupCreatorId() {
        return guideGroupCreatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_creator_id
     *
     * @param guideGroupCreatorId the value for guide_group_infos.guide_group_creator_id
     *
     * @mbggenerated
     */
    public void setGuideGroupCreatorId(Long guideGroupCreatorId) {
        this.guideGroupCreatorId = guideGroupCreatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_coupon_count
     *
     * @return the value of guide_group_infos.guide_group_coupon_count
     *
     * @mbggenerated
     */
    public Integer getGuideGroupCouponCount() {
        return guideGroupCouponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_coupon_count
     *
     * @param guideGroupCouponCount the value for guide_group_infos.guide_group_coupon_count
     *
     * @mbggenerated
     */
    public void setGuideGroupCouponCount(Integer guideGroupCouponCount) {
        this.guideGroupCouponCount = guideGroupCouponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_coupon_state
     *
     * @return the value of guide_group_infos.guide_group_coupon_state
     *
     * @mbggenerated
     */
    public Integer getGuideGroupCouponState() {
        return guideGroupCouponState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_coupon_state
     *
     * @param guideGroupCouponState the value for guide_group_infos.guide_group_coupon_state
     *
     * @mbggenerated
     */
    public void setGuideGroupCouponState(Integer guideGroupCouponState) {
        this.guideGroupCouponState = guideGroupCouponState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_coupon_publishtime
     *
     * @return the value of guide_group_infos.guide_group_coupon_publishtime
     *
     * @mbggenerated
     */
    public Date getGuideGroupCouponPublishtime() {
        return guideGroupCouponPublishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_coupon_publishtime
     *
     * @param guideGroupCouponPublishtime the value for guide_group_infos.guide_group_coupon_publishtime
     *
     * @mbggenerated
     */
    public void setGuideGroupCouponPublishtime(Date guideGroupCouponPublishtime) {
        this.guideGroupCouponPublishtime = guideGroupCouponPublishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_coupon_id
     *
     * @return the value of guide_group_infos.guide_group_coupon_id
     *
     * @mbggenerated
     */
    public Long getGuideGroupCouponId() {
        return guideGroupCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_coupon_id
     *
     * @param guideGroupCouponId the value for guide_group_infos.guide_group_coupon_id
     *
     * @mbggenerated
     */
    public void setGuideGroupCouponId(Long guideGroupCouponId) {
        this.guideGroupCouponId = guideGroupCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_agency_id
     *
     * @return the value of guide_group_infos.guide_group_agency_id
     *
     * @mbggenerated
     */
    public Long getGuideGroupAgencyId() {
        return guideGroupAgencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_agency_id
     *
     * @param guideGroupAgencyId the value for guide_group_infos.guide_group_agency_id
     *
     * @mbggenerated
     */
    public void setGuideGroupAgencyId(Long guideGroupAgencyId) {
        this.guideGroupAgencyId = guideGroupAgencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_infos.guide_group_end_time
     *
     * @return the value of guide_group_infos.guide_group_end_time
     *
     * @mbggenerated
     */
    public Date getGuideGroupEndTime() {
        return guideGroupEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_infos.guide_group_end_time
     *
     * @param guideGroupEndTime the value for guide_group_infos.guide_group_end_time
     *
     * @mbggenerated
     */
    public void setGuideGroupEndTime(Date guideGroupEndTime) {
        this.guideGroupEndTime = guideGroupEndTime;
    }

    public GuideAgencyInfos getGuideAgencyInfos() {
        return guideAgencyInfos;
    }

    public void setGuideAgencyInfos(GuideAgencyInfos guideAgencyInfos) {
        this.guideAgencyInfos = guideAgencyInfos;
    }

    public Admin getAdmin() {
        return admin;
    }

    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }

    public CouponScheme getCouponScheme() {
        return couponScheme;
    }

    public void setCouponScheme(CouponScheme couponScheme) {
        this.couponScheme = couponScheme;
    }

    public String getGuideGroupCouponInfo() {
        return guideGroupCouponInfo;
    }

    public void setGuideGroupCouponInfo(String guideGroupCouponInfo) {
        this.guideGroupCouponInfo = guideGroupCouponInfo;
    }
}