package org.entity.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GuideGroupInfosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;


    protected Integer limitStart;

    protected Integer limitEnd;

    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    public Integer getLimitStart() {
        return limitStart;
    }

    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public GuideGroupInfosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGuideGroupIdIsNull() {
            addCriterion("guide_group_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdIsNotNull() {
            addCriterion("guide_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdEqualTo(Long value) {
            addCriterion("guide_group_id =", value, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdNotEqualTo(Long value) {
            addCriterion("guide_group_id <>", value, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdGreaterThan(Long value) {
            addCriterion("guide_group_id >", value, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_group_id >=", value, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdLessThan(Long value) {
            addCriterion("guide_group_id <", value, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_group_id <=", value, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdIn(List<Long> values) {
            addCriterion("guide_group_id in", values, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdNotIn(List<Long> values) {
            addCriterion("guide_group_id not in", values, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdBetween(Long value1, Long value2) {
            addCriterion("guide_group_id between", value1, value2, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_group_id not between", value1, value2, "guideGroupId");
            return (Criteria) this;
        }

        public Criteria andGuideIdIsNull() {
            addCriterion("guide_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideIdIsNotNull() {
            addCriterion("guide_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideIdEqualTo(Long value) {
            addCriterion("guide_id =", value, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideIdNotEqualTo(Long value) {
            addCriterion("guide_id <>", value, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideIdGreaterThan(Long value) {
            addCriterion("guide_id >", value, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_id >=", value, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideIdLessThan(Long value) {
            addCriterion("guide_id <", value, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_id <=", value, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideIdIn(List<Long> values) {
            addCriterion("guide_id in", values, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideIdNotIn(List<Long> values) {
            addCriterion("guide_id not in", values, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideIdBetween(Long value1, Long value2) {
            addCriterion("guide_id between", value1, value2, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_id not between", value1, value2, "guideId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeIsNull() {
            addCriterion("guide_group_start_time is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeIsNotNull() {
            addCriterion("guide_group_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeEqualTo(Date value) {
            addCriterion("guide_group_start_time =", value, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeNotEqualTo(Date value) {
            addCriterion("guide_group_start_time <>", value, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeGreaterThan(Date value) {
            addCriterion("guide_group_start_time >", value, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("guide_group_start_time >=", value, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeLessThan(Date value) {
            addCriterion("guide_group_start_time <", value, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("guide_group_start_time <=", value, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeIn(List<Date> values) {
            addCriterion("guide_group_start_time in", values, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeNotIn(List<Date> values) {
            addCriterion("guide_group_start_time not in", values, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeBetween(Date value1, Date value2) {
            addCriterion("guide_group_start_time between", value1, value2, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("guide_group_start_time not between", value1, value2, "guideGroupStartTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicIsNull() {
            addCriterion("guide_group_scenic is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicIsNotNull() {
            addCriterion("guide_group_scenic is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicEqualTo(String value) {
            addCriterion("guide_group_scenic =", value, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicNotEqualTo(String value) {
            addCriterion("guide_group_scenic <>", value, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicGreaterThan(String value) {
            addCriterion("guide_group_scenic >", value, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicGreaterThanOrEqualTo(String value) {
            addCriterion("guide_group_scenic >=", value, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicLessThan(String value) {
            addCriterion("guide_group_scenic <", value, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicLessThanOrEqualTo(String value) {
            addCriterion("guide_group_scenic <=", value, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicLike(String value) {
            addCriterion("guide_group_scenic like", value, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicNotLike(String value) {
            addCriterion("guide_group_scenic not like", value, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicIn(List<String> values) {
            addCriterion("guide_group_scenic in", values, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicNotIn(List<String> values) {
            addCriterion("guide_group_scenic not in", values, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicBetween(String value1, String value2) {
            addCriterion("guide_group_scenic between", value1, value2, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupScenicNotBetween(String value1, String value2) {
            addCriterion("guide_group_scenic not between", value1, value2, "guideGroupScenic");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountIsNull() {
            addCriterion("guide_group_headcount is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountIsNotNull() {
            addCriterion("guide_group_headcount is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountEqualTo(Integer value) {
            addCriterion("guide_group_headcount =", value, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountNotEqualTo(Integer value) {
            addCriterion("guide_group_headcount <>", value, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountGreaterThan(Integer value) {
            addCriterion("guide_group_headcount >", value, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("guide_group_headcount >=", value, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountLessThan(Integer value) {
            addCriterion("guide_group_headcount <", value, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountLessThanOrEqualTo(Integer value) {
            addCriterion("guide_group_headcount <=", value, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountIn(List<Integer> values) {
            addCriterion("guide_group_headcount in", values, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountNotIn(List<Integer> values) {
            addCriterion("guide_group_headcount not in", values, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_headcount between", value1, value2, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupHeadcountNotBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_headcount not between", value1, value2, "guideGroupHeadcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountIsNull() {
            addCriterion("guide_group_ridingcount is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountIsNotNull() {
            addCriterion("guide_group_ridingcount is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountEqualTo(Integer value) {
            addCriterion("guide_group_ridingcount =", value, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountNotEqualTo(Integer value) {
            addCriterion("guide_group_ridingcount <>", value, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountGreaterThan(Integer value) {
            addCriterion("guide_group_ridingcount >", value, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("guide_group_ridingcount >=", value, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountLessThan(Integer value) {
            addCriterion("guide_group_ridingcount <", value, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountLessThanOrEqualTo(Integer value) {
            addCriterion("guide_group_ridingcount <=", value, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountIn(List<Integer> values) {
            addCriterion("guide_group_ridingcount in", values, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountNotIn(List<Integer> values) {
            addCriterion("guide_group_ridingcount not in", values, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_ridingcount between", value1, value2, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRidingcountNotBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_ridingcount not between", value1, value2, "guideGroupRidingcount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateIsNull() {
            addCriterion("guide_group_state is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateIsNotNull() {
            addCriterion("guide_group_state is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateEqualTo(Integer value) {
            addCriterion("guide_group_state =", value, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateNotEqualTo(Integer value) {
            addCriterion("guide_group_state <>", value, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateGreaterThan(Integer value) {
            addCriterion("guide_group_state >", value, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("guide_group_state >=", value, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateLessThan(Integer value) {
            addCriterion("guide_group_state <", value, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateLessThanOrEqualTo(Integer value) {
            addCriterion("guide_group_state <=", value, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateIn(List<Integer> values) {
            addCriterion("guide_group_state in", values, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateNotIn(List<Integer> values) {
            addCriterion("guide_group_state not in", values, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_state between", value1, value2, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupStateNotBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_state not between", value1, value2, "guideGroupState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkIsNull() {
            addCriterion("guide_group_remark is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkIsNotNull() {
            addCriterion("guide_group_remark is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkEqualTo(String value) {
            addCriterion("guide_group_remark =", value, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkNotEqualTo(String value) {
            addCriterion("guide_group_remark <>", value, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkGreaterThan(String value) {
            addCriterion("guide_group_remark >", value, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("guide_group_remark >=", value, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkLessThan(String value) {
            addCriterion("guide_group_remark <", value, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkLessThanOrEqualTo(String value) {
            addCriterion("guide_group_remark <=", value, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkLike(String value) {
            addCriterion("guide_group_remark like", value, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkNotLike(String value) {
            addCriterion("guide_group_remark not like", value, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkIn(List<String> values) {
            addCriterion("guide_group_remark in", values, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkNotIn(List<String> values) {
            addCriterion("guide_group_remark not in", values, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkBetween(String value1, String value2) {
            addCriterion("guide_group_remark between", value1, value2, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupRemarkNotBetween(String value1, String value2) {
            addCriterion("guide_group_remark not between", value1, value2, "guideGroupRemark");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdIsNull() {
            addCriterion("guide_group_creator_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdIsNotNull() {
            addCriterion("guide_group_creator_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdEqualTo(Long value) {
            addCriterion("guide_group_creator_id =", value, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdNotEqualTo(Long value) {
            addCriterion("guide_group_creator_id <>", value, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdGreaterThan(Long value) {
            addCriterion("guide_group_creator_id >", value, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_group_creator_id >=", value, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdLessThan(Long value) {
            addCriterion("guide_group_creator_id <", value, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_group_creator_id <=", value, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdIn(List<Long> values) {
            addCriterion("guide_group_creator_id in", values, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdNotIn(List<Long> values) {
            addCriterion("guide_group_creator_id not in", values, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdBetween(Long value1, Long value2) {
            addCriterion("guide_group_creator_id between", value1, value2, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCreatorIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_group_creator_id not between", value1, value2, "guideGroupCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountIsNull() {
            addCriterion("guide_group_coupon_count is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountIsNotNull() {
            addCriterion("guide_group_coupon_count is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountEqualTo(Integer value) {
            addCriterion("guide_group_coupon_count =", value, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountNotEqualTo(Integer value) {
            addCriterion("guide_group_coupon_count <>", value, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountGreaterThan(Integer value) {
            addCriterion("guide_group_coupon_count >", value, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("guide_group_coupon_count >=", value, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountLessThan(Integer value) {
            addCriterion("guide_group_coupon_count <", value, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountLessThanOrEqualTo(Integer value) {
            addCriterion("guide_group_coupon_count <=", value, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountIn(List<Integer> values) {
            addCriterion("guide_group_coupon_count in", values, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountNotIn(List<Integer> values) {
            addCriterion("guide_group_coupon_count not in", values, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_coupon_count between", value1, value2, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponCountNotBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_coupon_count not between", value1, value2, "guideGroupCouponCount");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateIsNull() {
            addCriterion("guide_group_coupon_state is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateIsNotNull() {
            addCriterion("guide_group_coupon_state is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateEqualTo(Integer value) {
            addCriterion("guide_group_coupon_state =", value, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateNotEqualTo(Integer value) {
            addCriterion("guide_group_coupon_state <>", value, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateGreaterThan(Integer value) {
            addCriterion("guide_group_coupon_state >", value, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("guide_group_coupon_state >=", value, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateLessThan(Integer value) {
            addCriterion("guide_group_coupon_state <", value, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateLessThanOrEqualTo(Integer value) {
            addCriterion("guide_group_coupon_state <=", value, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateIn(List<Integer> values) {
            addCriterion("guide_group_coupon_state in", values, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateNotIn(List<Integer> values) {
            addCriterion("guide_group_coupon_state not in", values, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_coupon_state between", value1, value2, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponStateNotBetween(Integer value1, Integer value2) {
            addCriterion("guide_group_coupon_state not between", value1, value2, "guideGroupCouponState");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeIsNull() {
            addCriterion("guide_group_coupon_publishtime is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeIsNotNull() {
            addCriterion("guide_group_coupon_publishtime is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeEqualTo(Date value) {
            addCriterion("guide_group_coupon_publishtime =", value, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeNotEqualTo(Date value) {
            addCriterion("guide_group_coupon_publishtime <>", value, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeGreaterThan(Date value) {
            addCriterion("guide_group_coupon_publishtime >", value, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("guide_group_coupon_publishtime >=", value, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeLessThan(Date value) {
            addCriterion("guide_group_coupon_publishtime <", value, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeLessThanOrEqualTo(Date value) {
            addCriterion("guide_group_coupon_publishtime <=", value, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeIn(List<Date> values) {
            addCriterion("guide_group_coupon_publishtime in", values, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeNotIn(List<Date> values) {
            addCriterion("guide_group_coupon_publishtime not in", values, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeBetween(Date value1, Date value2) {
            addCriterion("guide_group_coupon_publishtime between", value1, value2, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponPublishtimeNotBetween(Date value1, Date value2) {
            addCriterion("guide_group_coupon_publishtime not between", value1, value2, "guideGroupCouponPublishtime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdIsNull() {
            addCriterion("guide_group_coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdIsNotNull() {
            addCriterion("guide_group_coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdEqualTo(Long value) {
            addCriterion("guide_group_coupon_id =", value, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdNotEqualTo(Long value) {
            addCriterion("guide_group_coupon_id <>", value, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdGreaterThan(Long value) {
            addCriterion("guide_group_coupon_id >", value, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_group_coupon_id >=", value, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdLessThan(Long value) {
            addCriterion("guide_group_coupon_id <", value, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_group_coupon_id <=", value, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdIn(List<Long> values) {
            addCriterion("guide_group_coupon_id in", values, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdNotIn(List<Long> values) {
            addCriterion("guide_group_coupon_id not in", values, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdBetween(Long value1, Long value2) {
            addCriterion("guide_group_coupon_id between", value1, value2, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupCouponIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_group_coupon_id not between", value1, value2, "guideGroupCouponId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdIsNull() {
            addCriterion("guide_group_agency_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdIsNotNull() {
            addCriterion("guide_group_agency_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdEqualTo(Long value) {
            addCriterion("guide_group_agency_id =", value, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdNotEqualTo(Long value) {
            addCriterion("guide_group_agency_id <>", value, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdGreaterThan(Long value) {
            addCriterion("guide_group_agency_id >", value, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_group_agency_id >=", value, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdLessThan(Long value) {
            addCriterion("guide_group_agency_id <", value, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_group_agency_id <=", value, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdIn(List<Long> values) {
            addCriterion("guide_group_agency_id in", values, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdNotIn(List<Long> values) {
            addCriterion("guide_group_agency_id not in", values, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdBetween(Long value1, Long value2) {
            addCriterion("guide_group_agency_id between", value1, value2, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupAgencyIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_group_agency_id not between", value1, value2, "guideGroupAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeIsNull() {
            addCriterion("guide_group_end_time is null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeIsNotNull() {
            addCriterion("guide_group_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeEqualTo(Date value) {
            addCriterion("guide_group_end_time =", value, "guideGroupEndTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeNotEqualTo(Date value) {
            addCriterion("guide_group_end_time <>", value, "guideGroupEndTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeGreaterThan(Date value) {
            addCriterion("guide_group_end_time >", value, "guideGroupEndTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("guide_group_end_time >=", value, "guideGroupEndTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeLessThan(Date value) {
            addCriterion("guide_group_end_time <", value, "guideGroupEndTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("guide_group_end_time <=", value, "guideGroupEndTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeIn(List<Date> values) {
            addCriterion("guide_group_end_time in", values, "guideGroupEndTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeNotIn(List<Date> values) {
            addCriterion("guide_group_end_time not in", values, "guideGroupEndTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeBetween(Date value1, Date value2) {
            addCriterion("guide_group_end_time between", value1, value2, "guideGroupEndTime");
            return (Criteria) this;
        }

        public Criteria andGuideGroupEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("guide_group_end_time not between", value1, value2, "guideGroupEndTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guide_group_infos
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guide_group_infos
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}