package org.entity.dto;

import java.io.Serializable;

public class GuideGroupUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_user.guide_group_id
     *
     * @mbggenerated
     */
    private Long guideGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_group_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_group_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_user.id
     *
     * @return the value of guide_group_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_user.id
     *
     * @param id the value for guide_group_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_user.guide_group_id
     *
     * @return the value of guide_group_user.guide_group_id
     *
     * @mbggenerated
     */
    public Long getGuideGroupId() {
        return guideGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_user.guide_group_id
     *
     * @param guideGroupId the value for guide_group_user.guide_group_id
     *
     * @mbggenerated
     */
    public void setGuideGroupId(Long guideGroupId) {
        this.guideGroupId = guideGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_group_user.user_id
     *
     * @return the value of guide_group_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_group_user.user_id
     *
     * @param userId the value for guide_group_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}