package org.entity.dto;

import java.util.ArrayList;
import java.util.List;

public class GuideAgencyInfosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public GuideAgencyInfosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGuideAgencyIdIsNull() {
            addCriterion("guide_agency_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdIsNotNull() {
            addCriterion("guide_agency_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdEqualTo(Long value) {
            addCriterion("guide_agency_id =", value, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdNotEqualTo(Long value) {
            addCriterion("guide_agency_id <>", value, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdGreaterThan(Long value) {
            addCriterion("guide_agency_id >", value, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_agency_id >=", value, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdLessThan(Long value) {
            addCriterion("guide_agency_id <", value, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_agency_id <=", value, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdIn(List<Long> values) {
            addCriterion("guide_agency_id in", values, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdNotIn(List<Long> values) {
            addCriterion("guide_agency_id not in", values, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdBetween(Long value1, Long value2) {
            addCriterion("guide_agency_id between", value1, value2, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_agency_id not between", value1, value2, "guideAgencyId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameIsNull() {
            addCriterion("guide_agency_name is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameIsNotNull() {
            addCriterion("guide_agency_name is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameEqualTo(String value) {
            addCriterion("guide_agency_name =", value, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameNotEqualTo(String value) {
            addCriterion("guide_agency_name <>", value, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameGreaterThan(String value) {
            addCriterion("guide_agency_name >", value, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameGreaterThanOrEqualTo(String value) {
            addCriterion("guide_agency_name >=", value, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameLessThan(String value) {
            addCriterion("guide_agency_name <", value, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameLessThanOrEqualTo(String value) {
            addCriterion("guide_agency_name <=", value, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameLike(String value) {
            addCriterion("guide_agency_name like", value, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameNotLike(String value) {
            addCriterion("guide_agency_name not like", value, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameIn(List<String> values) {
            addCriterion("guide_agency_name in", values, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameNotIn(List<String> values) {
            addCriterion("guide_agency_name not in", values, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameBetween(String value1, String value2) {
            addCriterion("guide_agency_name between", value1, value2, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyNameNotBetween(String value1, String value2) {
            addCriterion("guide_agency_name not between", value1, value2, "guideAgencyName");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdIsNull() {
            addCriterion("guide_agency_principal_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdIsNotNull() {
            addCriterion("guide_agency_principal_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdEqualTo(Long value) {
            addCriterion("guide_agency_principal_id =", value, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdNotEqualTo(Long value) {
            addCriterion("guide_agency_principal_id <>", value, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdGreaterThan(Long value) {
            addCriterion("guide_agency_principal_id >", value, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_agency_principal_id >=", value, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdLessThan(Long value) {
            addCriterion("guide_agency_principal_id <", value, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_agency_principal_id <=", value, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdIn(List<Long> values) {
            addCriterion("guide_agency_principal_id in", values, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdNotIn(List<Long> values) {
            addCriterion("guide_agency_principal_id not in", values, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdBetween(Long value1, Long value2) {
            addCriterion("guide_agency_principal_id between", value1, value2, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyPrincipalIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_agency_principal_id not between", value1, value2, "guideAgencyPrincipalId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountIsNull() {
            addCriterion("guide_agency_riding_count is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountIsNotNull() {
            addCriterion("guide_agency_riding_count is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountEqualTo(Long value) {
            addCriterion("guide_agency_riding_count =", value, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountNotEqualTo(Long value) {
            addCriterion("guide_agency_riding_count <>", value, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountGreaterThan(Long value) {
            addCriterion("guide_agency_riding_count >", value, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_agency_riding_count >=", value, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountLessThan(Long value) {
            addCriterion("guide_agency_riding_count <", value, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountLessThanOrEqualTo(Long value) {
            addCriterion("guide_agency_riding_count <=", value, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountIn(List<Long> values) {
            addCriterion("guide_agency_riding_count in", values, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountNotIn(List<Long> values) {
            addCriterion("guide_agency_riding_count not in", values, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountBetween(Long value1, Long value2) {
            addCriterion("guide_agency_riding_count between", value1, value2, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRidingCountNotBetween(Long value1, Long value2) {
            addCriterion("guide_agency_riding_count not between", value1, value2, "guideAgencyRidingCount");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkIsNull() {
            addCriterion("guide_agency_remark is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkIsNotNull() {
            addCriterion("guide_agency_remark is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkEqualTo(String value) {
            addCriterion("guide_agency_remark =", value, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkNotEqualTo(String value) {
            addCriterion("guide_agency_remark <>", value, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkGreaterThan(String value) {
            addCriterion("guide_agency_remark >", value, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("guide_agency_remark >=", value, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkLessThan(String value) {
            addCriterion("guide_agency_remark <", value, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkLessThanOrEqualTo(String value) {
            addCriterion("guide_agency_remark <=", value, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkLike(String value) {
            addCriterion("guide_agency_remark like", value, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkNotLike(String value) {
            addCriterion("guide_agency_remark not like", value, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkIn(List<String> values) {
            addCriterion("guide_agency_remark in", values, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkNotIn(List<String> values) {
            addCriterion("guide_agency_remark not in", values, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkBetween(String value1, String value2) {
            addCriterion("guide_agency_remark between", value1, value2, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyRemarkNotBetween(String value1, String value2) {
            addCriterion("guide_agency_remark not between", value1, value2, "guideAgencyRemark");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdIsNull() {
            addCriterion("guide_agency_creator_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdIsNotNull() {
            addCriterion("guide_agency_creator_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdEqualTo(Long value) {
            addCriterion("guide_agency_creator_id =", value, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdNotEqualTo(Long value) {
            addCriterion("guide_agency_creator_id <>", value, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdGreaterThan(Long value) {
            addCriterion("guide_agency_creator_id >", value, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_agency_creator_id >=", value, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdLessThan(Long value) {
            addCriterion("guide_agency_creator_id <", value, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_agency_creator_id <=", value, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdIn(List<Long> values) {
            addCriterion("guide_agency_creator_id in", values, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdNotIn(List<Long> values) {
            addCriterion("guide_agency_creator_id not in", values, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdBetween(Long value1, Long value2) {
            addCriterion("guide_agency_creator_id between", value1, value2, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCreatorIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_agency_creator_id not between", value1, value2, "guideAgencyCreatorId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicIsNull() {
            addCriterion("guide_agency_scenic is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicIsNotNull() {
            addCriterion("guide_agency_scenic is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicEqualTo(String value) {
            addCriterion("guide_agency_scenic =", value, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicNotEqualTo(String value) {
            addCriterion("guide_agency_scenic <>", value, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicGreaterThan(String value) {
            addCriterion("guide_agency_scenic >", value, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicGreaterThanOrEqualTo(String value) {
            addCriterion("guide_agency_scenic >=", value, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicLessThan(String value) {
            addCriterion("guide_agency_scenic <", value, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicLessThanOrEqualTo(String value) {
            addCriterion("guide_agency_scenic <=", value, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicLike(String value) {
            addCriterion("guide_agency_scenic like", value, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicNotLike(String value) {
            addCriterion("guide_agency_scenic not like", value, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicIn(List<String> values) {
            addCriterion("guide_agency_scenic in", values, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicNotIn(List<String> values) {
            addCriterion("guide_agency_scenic not in", values, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicBetween(String value1, String value2) {
            addCriterion("guide_agency_scenic between", value1, value2, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyScenicNotBetween(String value1, String value2) {
            addCriterion("guide_agency_scenic not between", value1, value2, "guideAgencyScenic");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrIsNull() {
            addCriterion("guide_agency_addr is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrIsNotNull() {
            addCriterion("guide_agency_addr is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrEqualTo(String value) {
            addCriterion("guide_agency_addr =", value, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrNotEqualTo(String value) {
            addCriterion("guide_agency_addr <>", value, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrGreaterThan(String value) {
            addCriterion("guide_agency_addr >", value, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrGreaterThanOrEqualTo(String value) {
            addCriterion("guide_agency_addr >=", value, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrLessThan(String value) {
            addCriterion("guide_agency_addr <", value, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrLessThanOrEqualTo(String value) {
            addCriterion("guide_agency_addr <=", value, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrLike(String value) {
            addCriterion("guide_agency_addr like", value, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrNotLike(String value) {
            addCriterion("guide_agency_addr not like", value, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrIn(List<String> values) {
            addCriterion("guide_agency_addr in", values, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrNotIn(List<String> values) {
            addCriterion("guide_agency_addr not in", values, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrBetween(String value1, String value2) {
            addCriterion("guide_agency_addr between", value1, value2, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyAddrNotBetween(String value1, String value2) {
            addCriterion("guide_agency_addr not between", value1, value2, "guideAgencyAddr");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdIsNull() {
            addCriterion("guide_agency_city_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdIsNotNull() {
            addCriterion("guide_agency_city_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdEqualTo(Long value) {
            addCriterion("guide_agency_city_id =", value, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdNotEqualTo(Long value) {
            addCriterion("guide_agency_city_id <>", value, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdGreaterThan(Long value) {
            addCriterion("guide_agency_city_id >", value, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_agency_city_id >=", value, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdLessThan(Long value) {
            addCriterion("guide_agency_city_id <", value, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_agency_city_id <=", value, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdIn(List<Long> values) {
            addCriterion("guide_agency_city_id in", values, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdNotIn(List<Long> values) {
            addCriterion("guide_agency_city_id not in", values, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdBetween(Long value1, Long value2) {
            addCriterion("guide_agency_city_id between", value1, value2, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyCityIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_agency_city_id not between", value1, value2, "guideAgencyCityId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdIsNull() {
            addCriterion("guide_agency_province_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdIsNotNull() {
            addCriterion("guide_agency_province_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdEqualTo(Long value) {
            addCriterion("guide_agency_province_id =", value, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdNotEqualTo(Long value) {
            addCriterion("guide_agency_province_id <>", value, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdGreaterThan(Long value) {
            addCriterion("guide_agency_province_id >", value, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_agency_province_id >=", value, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdLessThan(Long value) {
            addCriterion("guide_agency_province_id <", value, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_agency_province_id <=", value, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdIn(List<Long> values) {
            addCriterion("guide_agency_province_id in", values, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdNotIn(List<Long> values) {
            addCriterion("guide_agency_province_id not in", values, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdBetween(Long value1, Long value2) {
            addCriterion("guide_agency_province_id between", value1, value2, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyProvinceIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_agency_province_id not between", value1, value2, "guideAgencyProvinceId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdIsNull() {
            addCriterion("guide_agency_manager_id is null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdIsNotNull() {
            addCriterion("guide_agency_manager_id is not null");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdEqualTo(Long value) {
            addCriterion("guide_agency_manager_id =", value, "guideAgencyManagerId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdNotEqualTo(Long value) {
            addCriterion("guide_agency_manager_id <>", value, "guideAgencyManagerId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdGreaterThan(Long value) {
            addCriterion("guide_agency_manager_id >", value, "guideAgencyManagerId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("guide_agency_manager_id >=", value, "guideAgencyManagerId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdLessThan(Long value) {
            addCriterion("guide_agency_manager_id <", value, "guideAgencyManagerId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdLessThanOrEqualTo(Long value) {
            addCriterion("guide_agency_manager_id <=", value, "guideAgencyManagerId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdIn(List<Long> values) {
            addCriterion("guide_agency_manager_id in", values, "guideAgencyManagerId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdNotIn(List<Long> values) {
            addCriterion("guide_agency_manager_id not in", values, "guideAgencyManagerId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdBetween(Long value1, Long value2) {
            addCriterion("guide_agency_manager_id between", value1, value2, "guideAgencyManagerId");
            return (Criteria) this;
        }

        public Criteria andGuideAgencyManagerIdNotBetween(Long value1, Long value2) {
            addCriterion("guide_agency_manager_id not between", value1, value2, "guideAgencyManagerId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guide_agency_infos
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guide_agency_infos
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}